# fluent-bit-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush         1
        Log_Level     info
        Daemon        off
        Parsers_File  parsers.conf
        HTTP_Server   On
        HTTP_Listen   0.0.0.0
        HTTP_Port     2020

    [INPUT]
        Name          tail
        Path          /var/log/*.log
        Parser        docker
        Tag           docker.*
        Refresh_Interval 5
        Mem_Buf_Limit 5MB

    [OUTPUT]
        Name          azure
        Match         *
        Customer_ID   YOUR_CUSTOMER_ID
        Shared_Key    YOUR_SHARED_KEY
        Log_Type      Trace
        Include_Tag   On

---
# fluent-bit-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fluent-bit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fluent-bit
  template:
    metadata:
      labels:
        app: fluent-bit
    spec:
      containers:
      - name: fluent-bit
        image: fluent/fluent-bit:latest
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: fluent-bit-config
          mountPath: /fluent-bit/etc/
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: fluent-bit-config
        configMap:
          name: fluent-bit-config

---
# fluent-bit-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: fluent-bit-service
spec:
  ports:
  - port: 2020
  selector:
    app: fluent-bit